module.exports = [
	"Introduction, first HTML page",
	"Hosting your site on Site44, HTML tags",
	"HTML tag attributes, the style attribute",
	"CSS styles and selectors, external stylesheets",
	"Portfolio Site",
	"Client Project Kickoff: Working with Clients",
	"The CSS Box Model (height, width, border, padding, margin, and box-sizing)",
	"The display and position styles",
	"Flexbox and media queries",
	"Client Project",
	"Javascript 101: the `<script>` tag",
	"Javascript 102: variables, loops, and functions",
	"Javascript 103: objects and arrays",
	"Javascript 104: working with the browser API",
	"Coin Flipping App",
	"jQuery 201: including jQuery on your site, selectors and methods",
	"jQuery 202: jQuery advanced methods, HTTP requests with jQuery - Part 1",
	"jQuery 203: HTTP requests with jQuery - Part 2",
	"Advanced Topics: Back End Web Development with Node.js",
	"Social Network Front End"
];
