module.exports = [
	"*Session 0* - Mon, Jun 6th - Introduction, first HTML page",
	"*Session 1* - Wed, Jun 8th - Command Line, Hosting your site on Firebase",
	"*Session 2* - Mon, Jun 13th - HTML tags & attributes, the `style` attribute",
	"*Session 3* - Wed, Jun 15th - CSS styles and selectors, external stylesheets",
	"*Session 4* - Mon, Jun 27th - Portfolio Site Show-and-Tell, Lab session",
	"*Session 5* - Wed, Jun 29th - Client Project Kickoff: Working with Clients",
	"*Session 6* - Mon, Jul 4th - Prebuilt & Customizable themes",
	"*Session 7* - Wed, Jul 6th - Bootstrap & CSS frameworks",
	"*Session 8* - Mon, Jul 11th - CSS layouts, the `display` style, flexbox & media queries",
	"*Session 9* - Wed, Jul 13th - Client Project Show-and-Tell, Lab session",
	"*Session 10* - Mon, Jul 18th - Javascript 101: the `<script>` tag",
	"*Session 11* - Wed, Jul 20th - Javascript 102: variables, loops, and functions",
	"*Session 12* - Mon, Jul 25th - Javascript 103: objects and arrays",
	"*Session 13* - Wed, Jul 27th - Javascript 104: working with the browser API",
	"*Session 14* - Mon, Aug 1st - TSA Randomizer project Show-and-Tell, Lab session",
	"*Session 15* - Wed, Aug 3rd - jQuery 201: including jQuery on your site",
	"*Session 16* - Mon, Aug 8th - jQuery 202: `$`, using jQuery selectors and methods",
	"*Session 17* - Wed, Aug 10th - jQuery 203: HTTP requests with jQuery",
	"*Session 18* - Mon, Aug 15th - Advanced Topics: Back End Web Development with Node.js",
	"*Session 19* - Wed, Aug 17th - Random Quote App Show-and-Tell, wrap-up/party :tada:"
]
