module.exports = {
    "members": [{
        "id": "U0LJQS17Z",
        "name": "arieann"
    }, {
        "id": "U0LGDQC2C",
        "name": "cooper"
    }, {
        "id": "U0LFQ0M5F",
        "name": "dannywalsh"
    }, {
        "id": "U0LBMKL8G",
        "name": "grader"
    }, {
        "id": "U0LBLSXD0",
        "name": "grader-beta"
    }, {
        "id": "U0LFKV3T3",
        "name": "joshweaver"
    }, {
        "id": "U0LGLRBRT",
        "name": "karen"
    }, {
        "id": "U0L47B7FV",
        "name": "ken"
    }, {
        "id": "U0LENLSVC",
        "name": "luisfernando19m"
    }, {
        "id": "U0LL1NR5E",
        "name": "maxjl"
    }, {
        "id": "U0LK9KUNP",
        "name": "subcurrent"
    }, {
        "id": "U0Q1DN1TR",
        "name": "tanaka"
    }, {
        "id": "U0LJU08LA",
        "name": "tgilboa"
    }, {
        "id": "U0LKS4KGU",
        "name": "xandern96"
    }, {
        "id": "USLACKBOT",
        "name": "slackbot"
    }],
}
